#!/usr/bin/env python3
"""
generate_report.py - Generate Markdown validation report

Usage:
    python generate_report.py <results_json> --output <output_file>
    
Example:
    python generate_report.py results.json --output report.md
"""

import argparse
import json
from datetime import datetime
from pathlib import Path


def generate_summary(results: dict) -> dict:
    """Generate summary statistics"""
    validation_results = results.get("validation_results", [])
    
    total_tables = len(validation_results)
    total_errors = sum(len(r.get("errors", [])) for r in validation_results)
    total_warnings = sum(len(r.get("warnings", [])) for r in validation_results)
    passed_tables = sum(1 for r in validation_results 
                       if not r.get("errors") and not r.get("warnings"))
    
    return {
        "total_tables": total_tables,
        "total_errors": total_errors,
        "total_warnings": total_warnings,
        "passed_tables": passed_tables
    }


def get_overall_status(summary: dict) -> tuple:
    """Get overall status"""
    if summary["total_errors"] > 0:
        return "❌ Issues Found", "error"
    elif summary["total_warnings"] > 0:
        return "⚠️ Has Warnings", "warning"
    else:
        return "✅ All Passed", "pass"


def generate_table_section(table_result: dict) -> str:
    """Generate report section for single table"""
    table_index = table_result.get("table_index", "?")
    headers = table_result.get("headers", [])
    errors = table_result.get("errors", [])
    warnings = table_result.get("warnings", [])
    matched_rules = table_result.get("matched_rules", "None")
    
    # Determine status icon
    if errors:
        status_icon = "❌"
    elif warnings:
        status_icon = "⚠️"
    else:
        status_icon = "✅"
    
    # Table name (using column combination)
    table_name = ", ".join(headers[:3]) if headers else "Unknown Table"
    if len(headers) > 3:
        table_name += "..."
    
    lines = [
        f"### Table {table_index}: {table_name} {status_icon}",
        "",
        f"**Identified Columns**: {', '.join(headers)}",
        f"**Applied Rules**: {matched_rules}",
        ""
    ]
    
    if errors or warnings:
        lines.extend([
            "| Row | Column | Rule | Issue | Severity |",
            "|-----|--------|------|-------|----------|"
        ])
        
        for error in errors:
            lines.append(
                f"| {error['row']} | {error['column']} | {error['rule_name']} | {error['message']} | ❌ Error |"
            )
        
        for warning in warnings:
            lines.append(
                f"| {warning['row']} | {warning['column']} | {warning['rule_name']} | {warning['message']} | ⚠️ Warning |"
            )
    else:
        lines.append("✅ All checks passed")
    
    lines.append("")
    return "\n".join(lines)


def generate_report(results: dict) -> str:
    """Generate complete report"""
    source_file = results.get("source_file", "unknown.docx")
    chapter = results.get("chapter", "Not specified")
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    summary = generate_summary(results)
    overall_status, _ = get_overall_status(summary)
    
    # Report header
    report_lines = [
        "# 📋 Document Validation Report",
        "",
        f"**Document**: `{source_file}`",
        f"**Chapter**: {chapter}",
        f"**Validation Time**: {timestamp}",
        f"**Result**: {overall_status}",
        "",
        "---",
        "",
        "## 📊 Summary",
        "",
        "| Item | Count |",
        "|------|-------|",
        f"| Tables Validated | {summary['total_tables']} |",
        f"| ❌ Errors | {summary['total_errors']} |",
        f"| ⚠️ Warnings | {summary['total_warnings']} |",
        f"| ✅ Passed | {summary['passed_tables']} |",
        "",
        "---",
        "",
        "## 📑 Detailed Results",
        ""
    ]
    
    # Each table result
    for table_result in results.get("validation_results", []):
        report_lines.append(generate_table_section(table_result))
    
    # Report footer
    report_lines.extend([
        "---",
        "",
        f"*Report generated at {timestamp}*"
    ])
    
    return "\n".join(report_lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate Markdown validation report",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument("results_json", help="Validation results JSON file (generated by validate_table.py)")
    parser.add_argument("--template", "-t", help="Report template file (optional)")
    parser.add_argument("--output", "-o", help="Output Markdown file path")
    
    args = parser.parse_args()
    
    # Read validation results
    results = json.loads(Path(args.results_json).read_text(encoding="utf-8"))
    
    # Generate report
    report = generate_report(results)
    
    # Output
    if args.output:
        Path(args.output).write_text(report, encoding="utf-8")
        print(f"Report saved to {args.output}")
    else:
        print(report)


if __name__ == "__main__":
    main()
